# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 385)
        MainWindow.setStyleSheet("background-color: beige;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_program = QtWidgets.QLabel(parent=self.centralwidget)
        self.lab_program.setGeometry(QtCore.QRect(320, -10, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lab_program.setFont(font)
        self.lab_program.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lab_program.setObjectName("lab_program")
        self.lineEdit_user = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_user.setGeometry(QtCore.QRect(330, 101, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_pass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_pass.setGeometry(QtCore.QRect(330, 170, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.but_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_login.setGeometry(QtCore.QRect(350, 240, 93, 28))
        self.but_login.setObjectName("but_login")
        self.but_forgot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_forgot.setGeometry(QtCore.QRect(320, 280, 151, 28))
        self.but_forgot.setObjectName("but_forgot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_program.setText(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Please enter your username:"))
        self.label_2.setText(_translate("MainWindow", "Please enter your password:"))
        self.but_login.setText(_translate("MainWindow", "Login"))
        self.but_forgot.setText(_translate("MainWindow", "I forgot my password"))
