# Form implementation generated from reading ui file 'c:\Users\Adam\OneDrive - University of Leeds\University Of Leeds Year 4\5870M - Individual Project\Python Files\guis\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(808, 406)
        MainWindow.setStyleSheet("background-color: beige;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab_program = QtWidgets.QLabel(parent=self.centralwidget)
        self.lab_program.setGeometry(QtCore.QRect(310, -10, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lab_program.setFont(font)
        self.lab_program.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lab_program.setObjectName("lab_program")
        self.lineEdit_user = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_user.setGeometry(QtCore.QRect(330, 90, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_user.setFont(font)
        self.lineEdit_user.setStyleSheet("border: 1px solid black;")
        self.lineEdit_user.setMaxLength(32)
        self.lineEdit_user.setObjectName("lineEdit_user")
        self.lab_user = QtWidgets.QLabel(parent=self.centralwidget)
        self.lab_user.setGeometry(QtCore.QRect(40, 90, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_user.setFont(font)
        self.lab_user.setObjectName("lab_user")
        self.lab_pass = QtWidgets.QLabel(parent=self.centralwidget)
        self.lab_pass.setGeometry(QtCore.QRect(40, 160, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lab_pass.setFont(font)
        self.lab_pass.setObjectName("lab_pass")
        self.lineEdit_pass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_pass.setGeometry(QtCore.QRect(330, 160, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_pass.setFont(font)
        self.lineEdit_pass.setStyleSheet("border: 1px solid black;")
        self.lineEdit_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_pass.setObjectName("lineEdit_pass")
        self.but_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_login.setGeometry(QtCore.QRect(350, 220, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_login.setFont(font)
        self.but_login.setStyleSheet("background-color: lightgray;\n"
"border: 1px solid black;")
        self.but_login.setObjectName("but_login")
        self.but_forgot = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_forgot.setGeometry(QtCore.QRect(310, 260, 171, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_forgot.setFont(font)
        self.but_forgot.setStyleSheet("background-color: lightgrey;\n"
"border: 1px solid black;")
        self.but_forgot.setObjectName("but_forgot")
        self.but_quit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.but_quit.setGeometry(QtCore.QRect(350, 300, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_quit.setFont(font)
        self.but_quit.setStyleSheet("background-color: lightgray;\n"
"border: 1px solid black;")
        self.but_quit.setObjectName("but_quit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab_program.setText(_translate("MainWindow", "Login"))
        self.lab_user.setText(_translate("MainWindow", "Please enter your username:"))
        self.lab_pass.setText(_translate("MainWindow", "Please enter your password:"))
        self.but_login.setText(_translate("MainWindow", "Login"))
        self.but_login.setShortcut(_translate("MainWindow", "Return"))
        self.but_forgot.setText(_translate("MainWindow", "I forgot my password"))
        self.but_quit.setText(_translate("MainWindow", "Quit"))
